# Generated by Django 5.2.14 on 2026-05-28 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0002_trainer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('session_date', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('objectives', models.TextField(blank=True)),
                ('teaching_method', models.CharField(blank=True, max_length=100)),
                ('materials', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=10)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainer')),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
    ]
