# Generated by Django 5.2.14 on 2026-05-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_alter_batchassignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_code', models.CharField(max_length=100)),
                ('batch_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('trainer_id', models.IntegerField()),
            ],
            options={
                'db_table': 'batches',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='batchassignment',
            options={'managed': False},
        ),
    ]
