# Generated by Django 5.2.14 on 2026-05-29 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='batch.batchassignment'),
        ),
    ]
