# Generated by assistant to safely rename DB column if needed
from django.db import migrations, connection


def forwards(apps, schema_editor):
    """If a legacy column 'join_date' exists in DB, rename it to 'joining_date'."""
    with connection.cursor() as cursor:
        cursor.execute("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trainers_trainer' AND COLUMN_NAME='join_date'")
        if cursor.fetchone()[0]:
            cursor.execute("ALTER TABLE trainers_trainer CHANGE `join_date` `joining_date` DATE NULL;")


def backwards(apps, schema_editor):
    """Reverse: if column 'joining_date' exists, rename back to 'join_date'."""
    with connection.cursor() as cursor:
        cursor.execute("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='trainers_trainer' AND COLUMN_NAME='joining_date'")
        if cursor.fetchone()[0]:
            cursor.execute("ALTER TABLE trainers_trainer CHANGE `joining_date` `join_date` DATE NULL;")


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_alter_trainer_options_trainer_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
