# Generated by Django 5.2.14 on 2026-05-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0006_unique_attendance_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('batch_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'participants',
                'managed': False,
            },
        ),
    ]
