# Generated by Django 5.2.14 on 2026-05-28 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('sessionplans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessionplans.sessionplan'),
        ),
    ]
