# Generated by Django 5.2.14 on 2026-05-28 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('roll_number', models.CharField(max_length=50)),
                ('internal_marks', models.FloatField(default=0.0)),
                ('practical_marks', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment')),
            ],
            options={
                'ordering': ['-final_score'],
            },
        ),
    ]
